# Generated by Django 2.2 on 2020-03-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('fajar', models.TimeField()),
                ('zuhar', models.TimeField()),
                ('asar', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('juma', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localities.Area')),
            ],
            options={
                'verbose_name': 'Masjid',
                'verbose_name_plural': 'Masajid',
            },
        ),
        migrations.CreateModel(
            name='MasjidStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=128)),
                ('phone', models.CharField(max_length=13)),
                ('action_count', models.PositiveSmallIntegerField(default=1, verbose_name='Actions till now')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjids.Masjid')),
            ],
        ),
    ]
