# Generated by Django 2.0 on 2020-03-08 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasjidStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=128)),
                ('phone', models.CharField(max_length=13)),
                ('action_count', models.PositiveSmallIntegerField(default=1, verbose_name='Actions till now')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='masjid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masjid',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AddField(
            model_name='masjidstaff',
            name='masjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjids.Masjid'),
        ),
    ]
