# Generated by Django 2.0 on 2020-03-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=2)),
            ],
        ),
    ]
