# Generated by Django 2.0 on 2020-03-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0002_ok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ok',
        ),
    ]
