# Generated by Django 2.0 on 2020-03-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0002_auto_20200302_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasjidAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=128)),
                ('phone', models.CharField(max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjids.Masjid')),
            ],
        ),
    ]
