# Generated by Django 2.0 on 2020-03-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0003_masjidadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasjidAdmin',
            new_name='MasjidStaff',
        ),
    ]
