# Generated by Django 2.0 on 2020-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0005_masjidstaff_action_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masjid',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
    ]
